handmade_atis_slots_to_qa = {
    "connect": ["where does the user want to connect?"],
    "depart_time.period_mod": ["what is the departure time period mod?"],
    "arrive_date.day_number": ["what day should the user arrive?"],
    "airport_name": ["what airport name does the user want to depart from?"],
    "stoploc.city_name": ["what city does the user want to stop at?"],
    "toloc.state_code": ["what's the state code of the user's destination?"],
    "restriction_code": ["what is the restriction?"],
    "period_of_day": ["what period of the day does the user want to depart at?"],
    "arrive_time.start_time": ["what is the arrive time?"],
    "day_number": ["how many days?"],
    "depart_date.date_relative": [
        "how many days from now does the user want to depart?"
    ],
    "flight_days": ["how many flight days?"],
    "city_name": ["what is the city name?"],
    "fare_basis_code": ["what is the fare basis code?"],
    "stoploc.state_code": ["what is the state code of the user's stop?"],
    "fromloc.state_name": ["what is the name of the user's departure state?"],
    "class_type": ["what is the class type of the user's flight?"],
    "return_date.day_number": ["what is the day number of the user's return date?"],
    "flight_stop": ["where will the flight stop?"],
    "return_date.today_relative": ["how many days from today will the user return at?"],
    "time_relative": ["how much time from right now will the user return at?"],
    "return_date.month_name": [
        "what is the name of the month at which the user will return?"
    ],
    "return_date.day_name": [
        "what is the name of the day at which the user will return?"
    ],
    "airline_name": ["what is the user's desired airline name?"],
    "depart_time.period_of_day": ["at what period of the day will the user depart?"],
    "depart_time.end_time": ["what is the end time of the departure?"],
    "state_code": ["what is the user's state code?"],
    "flight_mod": ["what is the flight mod?"],
    "toloc.country_name": ["what is the user's destination country?"],
    "fromloc.state_code": ["what is the departure's state code"],
    "airline_code": ["what is the code of the user's desired airline?"],
    "airport_code": ["what is the code of the user's desired airport?"],
    "time": ["what time is it?"],
    "arrive_date.day_name": ["what is the name of the day of the arrival?"],
    "return_time.period_of_day": ["what period of the day will the user return?"],
    "fromloc.airport_name": ["what is the departure airport name?"],
    "depart_date.year": ["what is the year of the departure?"],
    "state_name": ["what is the name of the state?"],
    "return_time.period_mod": ["what is the period mod of the return time?"],
    "toloc.city_name": ["what is the name of the destination city?"],
    "arrive_time.end_time": ["what is the latest time of the arrival?"],
    "stoploc.airport_name": [
        "what is the name of the airport in which the user will stop?"
    ],
    "stoploc.airport_code": [
        "what is the code of the airport in which the user will stop?"
    ],
    "cost_relative": ["how much will the cost be relative to what it is now?"],
    "depart_time.time_relative": [
        "how many days from now will the user's departure time be?"
    ],
    "meal_code": ["what is the meal code?"],
    "day_name": ["what is the name of the day?"],
    "economy": ["will the user fly in economy?"],
    "transport_type": ["what will the transport type be?"],
    "arrive_date.today_relative": ["how many days from now will the user arrive?"],
    "round_trip": ["will it be a round trip?"],
    "toloc.state_name": ["what is the name of the destination state?"],
    "arrive_time.time": ["what is the time of the user's arrival?"],
    "fromloc.city_name": ["what is the name of the city the user will travel from?"],
    "depart_time.time": ["what is the time of the departure?"],
    "depart_time.start_time": ["what is the start time of the departure?"],
    "days_code": ["what is the days code?"],
    "month_name": ["what is the name of the month?"],
    "arrive_date.date_relative": ["how many days from now will the user arrive?"],
    "arrive_time.period_of_day": ["what is the period of the day of the arrival?"],
    "toloc.airport_code": ["what is the code of the destination airport?"],
    "mod": ["what is the mod?"],
    "depart_date.day_name": ["what is the name of the day of the departure?"],
    "fare_amount": ["how much will the fare be?"],
    "toloc.airport_name": ["what is the name of the destination airport?"],
    "return_date.date_relative": ["how many days from now will the user return?"],
    "flight_number": ["what is the flight number?"],
    "arrive_date.month_name": ["what is the name of the month of the user's arrival?"],
    "arrive_time.period_mod": ["what is the period mod of the arrive time?"],
    "aircraft_code": ["what is the code of the aircraft?"],
    "depart_date.day_number": ["what is the day number of the departure date?"],
    "or": ["what is the or?"],
    "flight_time": ["at what time will the user's flight be?"],
    "depart_date.month_name": ["what is the name of the month of the departure?"],
    "depart_date.today_relative": [
        "how much time from now will the departure date be?"
    ],
    "arrive_time.time_relative": ["how much time from now will the user arrive?"],
    "meal": ["what meal did the user accept?"],
    "meal_description": ["can you describe the user's meal?"],
    "fromloc.airport_code": ["what is the code of the user's departure airport?"],
    "today_relative": ["what is the day relative from today?"],
    "compartment": ["what compartment will the user fly in?"],
    "booking_class": ["what is the user's preferred booking class?"],
    "flight": ["did the user mention flying?"],
}


qanlu_intent_to_qa = {
    "atis_airport": ["is the intent asking about an airport?"],
    "atis_distance": ["is the intent asking about the distance?"],
    "atis_flight_no": ["is the intent asking about a flight number?"],
    "atis_airfare": ["is the intent asking about an airfare?"],
    "atis_quantity": ["is the intent asking about how many?"],
    "atis_restriction": ["is the intent asking about any restrictions?"],
    "atis_flight": ["is the intent asking about a flight?"],
    "atis_abbreviation": ["is the intent asking about an abbreviation?"],
    "atis_aircraft": ["is the intent asking about an aircraft?"],
    "atis_cheapest": ["did they want the cheapest?"],
    "atis_city": ["is the intent asking about a city?"],
    "atis_day_name": ["is the intent asking about a day?"],
    "atis_airline": ["is the intent asking about an airline?"],
    "atis_meal": ["is the intent asking about a meal?"],
    "atis_flight_time": ["is the intent asking about flight time?"],
    "atis_capacity": ["is the intent asking about capacity?"],
    "atis_ground_fare": ["is the intent asking about ground fare?"],
    "atis_ground_service": ["is the intent asking about ground service?"],
}

qanlu_atis_slots_to_qa = {
    "aircraft_code": [
        "what aircraft code was mentioned?",
        "what aircraft code was specified?",
        "what aircraft code?",
        "what airplane code was mentioned?",
        "what airplane code was specified?",
        "what airplane code?",
    ],
    "airline_code": [
        "what airline code was mentioned?",
        "what airline code was specified?",
        "what airline code?",
    ],
    "airline_name": [
        "what airline name was mentioned?",
        "what airline name was specified?",
        "what airline name?",
    ],
    "airport_code": [
        "what airport code was mentioned?",
        "what airport code was specified?",
        "what airport code?",
    ],
    "airport_name": [
        "what airport name was mentioned?",
        "what airport name was specified?",
        "what airport name?",
    ],
    "arrive_date.date_relative": [
        "what was mentioned regarding flight arrival relative date?"
    ],
    "arrive_date.day_name": [
        "what flight arrival day was mentioned?",
        "what flight arrival day was specified?",
        "what flight arrival day?",
        "what is the flight arrival day?",
    ],
    "arrive_date.day_number": [
        "what flight arrival day number was mentioned?",
        "what flight arrival day number was specified?",
        "what flight arrival day number?",
        "what is the flight arrival day number?",
    ],
    "arrive_date.month_name": [
        "what month name was mentioned for flight arrival?",
        "what month name was specified for flight arrival?",
        "what flight arrival month name?",
        "what flight arrival month name was mentioned?",
    ],
    "arrive_date.today_relative": [
        "what day relative to today was mentioned for flight arrival?"
    ],
    "arrive_time.end_time": [
        "what was mentioned for end time regarding flight arrival?"
    ],
    "arrive_time.period_mod": [
        "what modifier was mentioned regarding flight arrival period of day?"
    ],
    "arrive_time.period_of_day": [
        "what was mentioned regarding flight arrival period of day?"
    ],
    "arrive_time.start_time": [
        "what was mentioned regarding flight arrival start time?"
    ],
    "arrive_time.time": ["what was mentioned regarding flight arrival time?"],
    "arrive_time.time_relative": [
        "what was mentioned regarding flight arrival time relative to a time or date?"
    ],
    "arrive_time": [
        "what flight arrival time was mentioned?",
        "what flight arrival time was specified?",
        "what flight arrival time?",
        "what time is the flight arrival",
    ],
    "booking_class": ["what booking class was mentioned?"],
    "city_name": [
        "what city name was mentioned?",
        "what city name was specified?",
        "what city name?",
    ],
    "class_type": [
        "what airfare class was mentioned?",
        "what airfare class was specified?",
        "what airfare class?",
    ],
    "compartment": ["what flight compartment was mentioned?"],
    "connect": ["what was mentioned about the flight regarding connection?"],
    "cost_relative": [
        "what relative price was mentioned?",
        "what relative price was specified?",
        "what relative price?",
    ],
    "days_code": ["what day code was mentioned?"],
    "day_name": ["what day name was mentioned?"],
    "day_number": ["what day number was mentioned?"],
    "depart_date.date_relative": [
        "what was mentioned regarding flight departure relative date?"
    ],
    "depart_date.day_name": [
        "what flight departure day name was mentioned?",
        "what flight departure day name was specified?",
        "what flight departure day name?",
        "what is the flight departure day name?",
    ],
    "depart_date.day_number": [
        "what flight departure day number was mentioned?",
        "what flight departure day number was specified?",
        "what flight departure day number?",
        "what is the flight departure day number?",
    ],
    "depart_date.month_name": [
        "what month name was mentioned for flight departure?",
        "what month name was specified for flight departure?",
        "what flight departure month name?",
        "what flight departure month name was mentioned?",
    ],
    "depart_date.today_relative": [
        "what flight departure relative day was mentioned?",
        "what flight departure relative day was specified?",
        "what flight departure relative day?",
        "what is the flight departure relative day?",
    ],
    "depart_date.year": [
        "what flight departure year was mentioned?",
        "what flight departure year was specified?",
        "what flight departure year?",
        "what is the flight departure year?",
    ],
    "depart_time.end_time": [
        "what was mentioned for end time regarding flight departure?"
    ],
    "depart_time.period_mod": [
        "what modifier was mentioned regarding flight departure period of day?"
    ],
    "depart_time.period_of_day": [
        "what was mentioned regarding flight departure period of day?"
    ],
    "depart_time.start_time": [
        "what was mentioned regarding flight departure start time?"
    ],
    "depart_time.time": [
        "what flight departure time was mentioned?",
        "what flight departure time was specified?",
        "what flight departure time?",
        "what time is the flight departure",
        "what was mentioned regarding flight departure time?",
    ],
    "depart_time.time_relative": [
        "what was mentioned regarding flight departure time relative to a time or date?"
    ],
    "economy": [
        "what was mentioned regarding economy class?",
        "what was specified regarding economy class?",
    ],
    "fare_amount": [
        "what price was mentioned?",
        "what price was specified?",
        "what price?",
    ],
    "fare_basis_code": ["what fare code was mentioned?"],
    "flight": ["what flight did they ask for?"],
    "flight_days": ["what was mentioned about flight days?"],
    "flight_mod": ["what modifier was specified for the flight?"],
    "flight_number": [
        "what flight number was mentioned?",
        "what flight number was specified?",
        "what flight number?",
    ],
    "flight_stop": ["what was specified about the flight's stops?"],
    "flight_time": ["what was mentioned about flight times?"],
    "fromloc.airport_code": [
        "what flight departure airport code was mentioned?",
        "what flight departure airport code was specified?",
        "what flight departure airport code?",
    ],
    "fromloc.airport_name": [
        "what flight departure airport name was mentioned?",
        "what flight departure airport name was specified?",
        "what flight departure airport name?",
    ],
    "fromloc.city_name": [
        "what flight departure city name was mentioned?",
        "what flight departure city name was specified?",
        "what flight departure city name?",
    ],
    "fromloc.state_code": [
        "what flight departure state code was mentioned?",
        "what flight departure state code was specified?",
        "what flight departure state code?",
    ],
    "fromloc.state_name": [
        "what flight departure state name was mentioned?",
        "what flight departure state name was specified?",
        "what flight departure state name?",
    ],
    "meal": ["what meal did they ask for?"],
    "meal_code": ["what meal code was mentioned"],
    "meal_description": ["what meal of the day was mentioned?"],
    "mod": ["what modifier was mentioned?"],
    "month_name": ["what month name was mentioned?"],
    "or": ["did they mention an alternative?"],
    "period_of_day": ["what period of day was mentioned?"],
    "restriction_code": ["what restriction code was mentioned?"],
    "return_date.date_relative": ["what was mentioned regarding return relative date?"],
    "return_date.day_name": ["what day name was mentioned for return?"],
    "return_date.day_number": ["what day number was mentioned regarding return date?"],
    "return_date.month_name": ["what month name was mentioned for return?"],
    "return_date.today_relative": [
        "what day relative to today was mentioned for return?"
    ],
    "return_time.period_mod": [
        "what modifier was mentioned regarding return period of day?"
    ],
    "return_time.period_of_day": ["what period of day was mentioned for return time?"],
    "round_trip": ["what was mentioned regarding round trip?"],
    "state_code": ["what state code was mentioned?"],
    "state_name": ["what state name was mentioned?"],
    "stoploc.airport_code": [
        "what airport code was mentioned for the stop?",
        "what airport code should the flight have a stop at?",
    ],
    "stoploc.airport_name": [
        "what airport name was mentioned for the stop?",
        "what airport name should the flight have a stop at?",
    ],
    "stoploc.city_name": [
        "what city name was mentioned for the stop?",
        "what city name should the flight have a stop at?",
    ],
    "stoploc.state_code": [
        "what state code was mentioned for the stop?",
        "what state code should the flight have a stop at?",
    ],
    "time": ["what time was mentioned?"],
    "time_relative": ["what relative time was mentioned?"],
    "today_relative": ["what day relative to today was mentioned?"],
    "toloc.airport_code": [
        "what flight arrival airport code was mentioned?",
        "what flight arrival airport code was specified?",
        "what flight arrival airport code?",
    ],
    "toloc.airport_name": [
        "what flight arrival airport name was mentioned?",
        "what flight arrival airport name was specified?",
        "what flight arrival airport name?",
    ],
    "toloc.city_name": [
        "what flight arrival city name was mentioned?",
        "what flight arrival city name was specified?",
        "what flight arrival city name?",
    ],
    "toloc.country_name": [
        "what flight arrival country name was mentioned?",
        "what flight arrival country name was specified?",
        "what flight arrival country name?",
    ],
    "toloc.state_code": [
        "what flight arrival state code was mentioned?",
        "what flight arrival state code was specified?",
        "what flight arrival state code?",
    ],
    "toloc.state_name": [
        "what flight arrival state name was mentioned?",
        "what flight arrival state name was specified?",
        "what flight arrival state name?",
    ],
    "transport_type": ["what transportation type was mentioned?"],
}

handmade_snips_slots_to_qa = {
    "restaurant_type": ["what restaurant type did the user specify?"],
    "spatial_relation": ["what spatial relation was specified by the user?"],
    "served_dish": ["what was the served dish?"],
    "facility": ["what facility was specified?"],
    "object_part_of_series_type": ["what object part of series type was specified?"],
    "party_size_description": ["what was the party size description?"],
    "object_type": ["what object type was mentioned by the person?"],
    "best_rating": ["what was the best rating?"],
    "geographic_poi": ["what was the geographic poi?"],
    "music_item": ["what music item was mentioned?"],
    "timerange": ["what time range was mentioned?"],
    "genre": ["what was the genre?"],
    "sort": ["where was sorting mentioned?"],
    "album": ["what was the album mentioned?"],
    "playlist": ["what was the mentioned playlist?"],
    "rating_unit": ["what is the rating unit?"],
    "poi": ["what was the poi?"],
    "artist": ["which artist was mentioned?"],
    "restaurant_name": ["what is the chosen restaurant name?"],
    "location_name": ["what was the location name?"],
    "movie_name": ["what was the movie name?"],
    "movie_type": ["what was the movie type?"],
    "object_location_type": ["what was the object location type?"],
    "object_name": ["what was the object name?"],
    "year": ["what was the year?"],
    "party_size_number": ["what was the party size?"],
    "playlist_owner": ["who was the playlist owner?"],
    "current_location": ["what is the user's current location?"],
    "object_select": ["which object was selected?"],
    "entity_name": ["what was the entity name?"],
    "service": ["what was the mentioned service?"],
    "city": ["what was the mentioned city?"],
    "track": ["what was the mentioned track?"],
    "cuisine": ["which cuisine was mentioned?"],
    "condition_temperature": ["what was the temperature?"],
    "state": ["what was the mentioned state?"],
    "rating_value": ["what was the rating?"],
    "country": ["which country was it?"],
    "condition_description": ["what was the description of the condition?"],
}

handmade_intent_to_qa = {
    "RateBook": ["is the intent asking about rating a book?"],
    "GetWeather": ["is the intent asking about getting the weather?"],
    "PlayMusic": ["is the intent asking about playing music?"],
    "AddToPlaylist": ["is the intent asking about adding to a playlist?"],
    "SearchScreeningEvent": [
        "is the intent asking about searching for a screening event?"
    ],
    "SearchCreativeWork": ["is the intent asking about searching for a creative work?"],
    "BookRestaurant": ["is the intent asking about booking a restaurant?"],
}

handmade_mwoz_slots_to_qa = {
    "hotel-pricerange": ["what hotel price range does the user want?"],
    "restaurant-pricerange": ["what restaurant price range does the user want?"],
    "hotel-type": ["what is the type of the hotel?"],
    "attraction-type": ["what is the type of the attraction?"],
    "hotel-book day": ["what is the day of the hotel booking?"],
    "restaurant-book day": ["what is the day of the restaurant booking?"],
    "hotel-book people": ["how many people should be booked in the hotel?"],
    "train-book people": ["how many tickets should be booked in the train?"],
    "restaurant-book people": ["how many people should be booked in the restaurant?"],
    "hotel-area": ["where is the hotel?"],
    "restaurant-area": ["where is the restaurant?"],
    "attraction-area": ["where is the attraction?"],
    "hotel-name": ["what is the name of the hotel?"],
    "attraction-name": ["what is the name of the attraction?"],
    "restaurant-name": ["what is the name of the restaurant?"],
    "train-destination": ["what is the train destination?"],
    "taxi-destination": ["what is the taxi destination?"],
    "taxi-departure": ["what is the taxi departure?"],
    "train-departure": ["what is the train departure?"],
    "train-arriveby": ["what time should the train arrive by?"],
    "taxi-arriveby": ["what time should the taxi arrive by?"],
    "train-leaveat": ["what time should the train leave at?"],
    "taxi-leaveat": ["what time should the taxi leave at?"],
    "restaurant-food": ["what kind of food should the restaurant serve?"],
    "restaurant-book time": ["what time should the restaurant be booked?"],
    "hotel-book stay": ["how long does the user want the stay to be booked for at the hotel?"],
    "hotel-parking": ["does the user want the hotel to have parking?"],
    "hotel-stars": ["how many hotel stars did the user want?"],
    "hotel-internet": ["did the user want the hotel to have internet?"],
    "train-day": ["in what day will the train leave?"],
}

gpt_3_mwoz_slots_to_qa = {
    "hotel-pricerange": ["What is the desired price range for the hotel?"],
    "restaurant-pricerange": ["What is the desired price range for the restaurant?"],
    "hotel-type": ["What type of hotel is desired?"],
    "attraction-type": ["What type of attraction is desired?"],
    "hotel-book day": ["On what day is the hotel booking requested?"],
    "restaurant-book day": ["On what day is the restaurant booking requested?"],
    "hotel-book people": ["How many people should be booked in the hotel?"],
    "train-book people": ["How many tickets should be booked on the train?"],
    "restaurant-book people": ["How many people should be booked at the restaurant?"],
    "hotel-area": ["Where is the desired location for the hotel?"],
    "restaurant-area": ["Where is the desired location for the restaurant?"],
    "attraction-area": ["Where is the desired location for the attraction?"],
    "hotel-name": ["What is the name of the desired hotel?"],
    "attraction-name": ["What is the name of the desired attraction?"],
    "restaurant-name": ["What is the name of the desired restaurant?"],
    "train-destination": ["What is the destination for the requested train?"],
    "taxi-destination": ["What is the destination for the requested taxi?"],
    "taxi-departure": ["What is the departure location for the requested taxi?"],
    "train-departure": ["What is the departure location for the requested train?"],
    "train-arriveby": ["What time should the train arrive at its destination?"],
    "taxi-arriveby": ["What time should the taxi arrive at its destination?"],
    "train-leaveat": ["What time should the train depart?"],
    "taxi-leaveat": ["What time should the taxi depart?"],
    "restaurant-food": ["What type of food should be served at the restaurant?"],
    "restaurant-book time": ["What time is the restaurant booking requested for?"],
    "hotel-book stay": ["How long is the hotel stay requested for?"],
    "hotel-parking": ["Is parking required at the hotel?"],
    "hotel-stars": ["How many stars should the hotel have?"],
    "hotel-internet": ["Is internet access required at the hotel?"],
    "train-day": ["On what day will the train depart?"],
}

gpt3_bad_mwoz_slots_to_qa = {
    "hotel-pricerange": ['What is the price range of the hotel?'],
    "restaurant-pricerange":['What is the price range of the restaurant?'], 
    "hotel-type": ['What type of hotel is the user looking for?'],
    "attraction-type": ['What type of attraction is the user looking for?'],
    "hotel-book day": ['On what day does the user want to book a hotel?'],
    "restaurant-book day": ['On what day does the user want to book a restaurant?'],
    "hotel-book people": ['How many people does the user want to book a hotel for?'],
    "train-book people": ['How many people does the user want to book a train for?'],
    "restaurant-book people": ['How many people does the user want to book a restaurant for?'], 
    "hotel-area": ['What area is the hotel located in?'],
    "restaurant-area": ['What area is the restaurant located in?'],
    "attraction-area": ['What area is the attraction located in?'],
    "hotel-name": ['What is the name of the hotel?'],
    "attraction-name": ['What is the name of the attraction?'],
    "restaurant-name": ['What is the name of the restaurant?'],
    "train-destination": ['What is the destination of the train?'],
    "taxi-destination": ['What is the destination of the taxi?'],
    "taxi-departure": ['What is the departure point for the taxi?'],
    "train-departure": ['What is the departure point for the train?'],
    "train-arriveby": ['What time does the user need to arrive by for the train?'],
    "taxi-arriveby": ['What time does the user need to arrive by for the taxi?'],
    "train-leaveat": ['What time does the user need to leave at for the train?'],
    "taxi-leaveat": ['What time does the user need to leave at for the taxi?'],
    "restaurant-food": ['What type of food does the user want at the restaurant?'],
    "restaurant-book time": ['What time does the user want to book the restaurant for?'],
    "hotel-book stay": ['How long does the user want to book the hotel for?'],
    "hotel-parking": ['Does the hotel have parking?'],
    "hotel-stars": ['How many stars does the hotel have?'],
    "hotel-internet": ['Does the hotel have internet access?'],
    "train-day": ['On what day does the user want to book the train?'],
}

gpt3_bad_mwoz_slots_to_qa_v2 = {
    "hotel-pricerange": ['What is the price range of the hotel?'],
    "restaurant-pricerange":['What is the price range of the restaurant?'], 
    "hotel-type": ['What type of hotel is the user looking for?'],
    "attraction-type": ['What type of attraction is the user looking for?'],
    "hotel-book day": ['On what day does the user want to book a hotel?'],
    "restaurant-book day": ['On what day does the user want to book a restaurant?'],
    "hotel-book people": ['How many people does the user want to book a hotel for?'],
    "train-book people": ['How many people does the user want to book a train for?'],
    "restaurant-book people": ['How many people does the user want to book a restaurant for?'], 
    "hotel-area": ['What area is the hotel located in?'],
    "restaurant-area": ['What area is the restaurant located in?'],
    "attraction-area": ['What area is the attraction located in?'],
    "hotel-name": ['What is the name of the hotel?'],
    "attraction-name": ['What is the name of the attraction?'],
    "restaurant-name": ['What is the name of the restaurant?'],
    "train-destination": ['What is the destination of the train?'],
    "taxi-destination": ['What is the destination of the taxi?'],
    "taxi-departure": ['What is the departure point for the taxi?'],
    "train-departure": ['What is the departure point for the train?'],
    "train-arriveby": ['What time does the train arrive by?'],
    "taxi-arriveby": ['What time does the taxi arrive by?'],
    "train-leaveat": ['What time does the train leave at?'],
    "taxi-leaveat": ['What time does the taxi leave at?'],
    "restaurant-food": ['What type of food does the user want at the restaurant?'],
    "restaurant-book time": ['What time does the user want to book the restaurant for?'],
    "hotel-book stay": ['How long does the user want to book the hotel for?'],
    "hotel-parking": ['Does the hotel have parking?'],
    "hotel-stars": ['How many stars does the hotel have?'],
    "hotel-internet": ['Does the hotel have internet access?'],
    "train-day": ['On what day does the user want to book the train?'],
}


mwoz_slots_to_qa_whatis = {
    "hotel-pricerange": ["what is the hotel pricerange?"],
    "restaurant-pricerange": ["what is the restaurant pricerange?"],
    "hotel-type": ["what is the hotel type?"],
    "attraction-type": ["what is the attraction type?"],
    "hotel-book day": ["what is the hotel book day?"],
    "restaurant-book day": ["what is the restaurant book day?"],
    "hotel-book people": ["what is the hotel book people?"],
    "train-book people": ["what is the train book people?"],
    "restaurant-book people": ["what is the restaurant book people?"],
    "hotel-area": ["what is the hotel area?"],
    "restaurant-area": ["what is the restaurant area?"],
    "attraction-area": ["what is the attraction area?"],
    "hotel-name": ["what is the hotel name?"],
    "attraction-name": ["what is the attraction name?"],
    "restaurant-name": ["what is the restaurant name?"],
    "train-destination": ["what is the train destination?"],
    "taxi-destination": ["what is the taxi destination?"],
    "taxi-departure": ["what is the taxi departure?"],
    "train-departure": ["what is the train departure?"],
    "train-arriveby": ["what is the train arriveby?"],
    "taxi-arriveby": ["what is the taxi arriveby?"],
    "train-leaveat": ["what is the train leaveat?"],
    "taxi-leaveat": ["what is the taxi leaveat?"],
    "restaurant-food": ["what is the restaurant food?"],
    "restaurant-book time": ["what is the restaurant book time?"],
    "hotel-book stay": ["what is the hotel book stay?"],
    "hotel-parking": ["what is the hotel parking?"],
    "hotel-stars": ["what is the hotel stars?"],
    "hotel-internet": ["what is the hotel internet?"],
    "train-day": ["what is the train day?"],
}

mwoz_slots_to_qa_whatis_slotvalue = {
    "hotel-pricerange": ["what is the value of the slot hotel pricerange?"],
    "restaurant-pricerange": ["what is the value of the slot restaurant pricerange?"],
    "hotel-type": ["what is the value of the slot hotel type?"],
    "attraction-type": ["what is the value of the slot attraction type?"],
    "hotel-book day": ["what is the value of the slot hotel book day?"],
    "restaurant-book day": ["what is the value of the slot restaurant book day?"],
    "hotel-book people": ["what is the value of the slot hotel book people?"],
    "train-book people": ["what is the value of the slot train book people?"],
    "restaurant-book people": ["what is the value of the slot restaurant book people?"],
    "hotel-area": ["what is the value of the slot hotel area?"],
    "restaurant-area": ["what is the value of the slot restaurant area?"],
    "attraction-area": ["what is the value of the slot attraction area?"],
    "hotel-name": ["what is the value of the slot hotel name?"],
    "attraction-name": ["what is the value of the slot attraction name?"],
    "restaurant-name": ["what is the value of the slot restaurant name?"],
    "train-destination": ["what is the value of the slot train destination?"],
    "taxi-destination": ["what is the value of the slot taxi destination?"],
    "taxi-departure": ["what is the value of the slot taxi departure?"],
    "train-departure": ["what is the value of the slot train departure?"],
    "train-arriveby": ["what is the value of the slot train arriveby?"],
    "taxi-arriveby": ["what is the value of the slot taxi arriveby?"],
    "train-leaveat": ["what is the value of the slot train leaveat?"],
    "taxi-leaveat": ["what is the value of the slot taxi leaveat?"],
    "restaurant-food": ["what is the value of the slot restaurant food?"],
    "restaurant-book time": ["what is the value of the slot restaurant book time?"],
    "hotel-book stay": ["what is the value of the slot hotel book stay?"],
    "hotel-parking": ["what is the value of the slot hotel parking?"],
    "hotel-stars": ["what is the value of the slot hotel stars?"],
    "hotel-internet": ["what is the value of the slot hotel internet?"],
    "train-day": ["what is the value of the slot train day?"],
}



mwoz_slots_to_qa_all = {
    "hotel-pricerange": [
        "what is the hotel pricerange?", 
        "what is the value of the slot hotel pricerange?",
        'What is the price range of the hotel?',
    ],
    "restaurant-pricerange": [
        "what is the restaurant pricerange?", 
        "what is the value of the slot restaurant pricerange?",
        'What is the price range of the restaurant?',
    ],
    "hotel-type": [
        "what is the hotel type?", 
        "what is the value of the slot hotel type?",
        'What type of hotel is the user looking for?',
    ],
    "attraction-type": [
        "what is the attraction type?", 
        "what is the value of the slot attraction type?",
        'What type of attraction is the user looking for?',
    ],
    "hotel-book day": [
        "what is the hotel book day?", 
        "what is the value of the slot hotel book day?",
        'On what day does the user want to book a hotel?',
    ],
    "restaurant-book day": [
        "what is the restaurant book day?", 
        "what is the value of the slot restaurant book day?",
        'On what day does the user want to book a restaurant?',
    ],
    "hotel-book people": [
        "what is the hotel book people?", 
        "what is the value of the slot hotel book people?",
        'How many people does the user want to book a hotel for?',
    ],
    "train-book people": [
        "what is the train book people?", 
        "what is the value of the slot train book people?",
        'How many people does the user want to book a train for?',
    ],
    "restaurant-book people": [
        "what is the restaurant book people?", 
        "what is the value of the slot restaurant book people?",
        'How many people does the user want to book a restaurant for?'
    ],
    "hotel-area": [
        "what is the hotel area?", 
        "what is the value of the slot hotel area?",
        'What area is the hotel located in?'
    ],
    "restaurant-area": [
        "what is the restaurant area?", 
        "what is the value of the slot restaurant area?",
        'What area is the restaurant located in?'
    ],
    "attraction-area": [
        "what is the attraction area?", 
        "what is the value of the slot attraction area?",
        'What area is the attraction located in?',
    ],
    "hotel-name": [
        "what is the hotel name?", 
        "what is the value of the slot hotel name",
        'What is the name of the hotel?',
    ],
    "attraction-name": [
        "what is the attraction name?", 
        "what is the value of the slot attraction name?",
        'What is the name of the attraction?',
    ],
    "restaurant-name": [
        "what is the restaurant name?", 
        "what is the value of the slot restaurant name?",
        'What is the name of the restaurant?',
    ],
    "train-destination": [
        "what is the train destination?", 
        "what is the value of the slot train destination?",
        'What is the destination of the train?',
    ],
    "taxi-destination": [
        "what is the taxi destination?", 
        "what is the value of the slot taxi destination?",
        'What is the destination of the taxi?',
    ],
    "taxi-departure": [
        "what is the taxi departure?", 
        "what is the value of the slot taxi departure?",
        'What is the departure point for the taxi?',
    ],
    "train-departure": [
        "what is the train departure?", 
        "what is the value of the slot train departure?",
        'What is the departure point for the train?',
    ],
    "train-arriveby": [
        "what is the train arriveby?", 
        "what is the value of the slot train arriveby?",
        'What time does the train arrive by?',
    ],
    "taxi-arriveby": [
        "what is the taxi arriveby?", 
        "what is the value of the slot taxi arriveby?",
        'What time does the taxi arrive by?',
    ],
    "train-leaveat": [
        "what is the train leaveat?", 
        "what is the value of the slot train leaveat?",
        'What time does the train leave at?',
    ],
    "taxi-leaveat": [
        "what is the taxi leaveat?", 
        "what is the value of the slot taxi leaveat?",
        'What time does the taxi leave at?',
    ],
    "restaurant-food": [
        "what is the restaurant food?", 
        "what is the value of the slot restaurant food?",
        'What type of food does the user want at the restaurant?',
    ],
    "restaurant-book time": [
        "what is the restaurant book time?", 
        "what is the value of the slot restaurant book time?",
        'What time does the user want to book the restaurant for?',
    ],
    "hotel-book stay": [
        "what is the hotel book stay?", 
        "what is the value of the slot hotel book stay?",
        'How long does the user want to book the hotel for?',
    ],
    "hotel-parking": [
        "what is the hotel parking?", 
        "what is the value of the slot hotel parking?",
        'Does the hotel have parking?',
    ],
    "hotel-stars": [
        "what is the hotel stars?", 
        "what is the value of the slot hotel stars?",
        'How many stars does the hotel have?',
    ],
    "hotel-internet": [
        "what is the hotel internet?", 
        "what is the value of the slot hotel internet?",
        'Does the hotel have internet access?',
    ],
    "train-day": [
        "what is the train day?", 
        "what is the value of the slot train day?",
        'On what day does the user want to book the train?',
    ],
}

gpt3_mwoz_slots_pronouns = {
    "hotel-pricerange": ["What is the price range of the hotel?"],
    "restaurant-pricerange":["What is the price range of the restaurant?"],
    "hotel-type": ["What type of hotel are you looking for?"],
    "attraction-type":["What type of attraction are you interested in?"],
    "hotel-book day":["On what day do you want to book the hotel?"],
    "restaurant-book day":["On what day do you want to book the restaurant?"],
    "hotel-book people": ["How many people are you booking the hotel for?"],
    "train-book people": ["How many people are you booking the train for?"],
    "restaurant-book people": ["How many people are you booking the restaurant for?"],
    "hotel-area":  ["What area is the hotel located in?"],
    "restaurant-area":  ["What area is the restaurant located in?"],
    "attraction-area":  ["What area is the attraction located in?"],
    "hotel-name":    ["What is the name of the hotel?"],
    "attraction-name":  ["What is the name of the attraction?"],
    "restaurant-name":  ["What is the name of the restaurant?"],
    "train-destination": ["What is the destination of the train?"],
    "taxi-destination":  ["What is the destination of the taxi?"],
    "taxi-departure":  ["What is the departure point of the taxi?"],
    "train-departure": ["What is the departure point of the train?"],
    "train-arriveby": ["What time do you need to arrive by on the train?"],
    "taxi-arriveby":  ["What time do you need to arrive by in the taxi?"],
    "train-leaveat":  ["What time do you need to leave at on the train?"],
    "taxi-leaveat": ["What time do you need to leave at in the taxi?"],
    "restaurant-food": ["What type of food does the restaurant serve?"],
    "restaurant-book time": ["What time do you want to book the restaurant for?"],
    "hotel-book stay": ["How long do you want to stay at the hotel?"],
    "hotel-parking": ["Does the hotel have parking?"],
    "hotel-stars": ["How many stars does the hotel have?"],
    "hotel-internet": ["Does the hotel have internet access?"],
    "train-day": ["On what day do you want to book the train?"],
}

gpt3_mwoz_slots_pronouns_manualtrain = {
    "hotel-pricerange": ["What is the price range of the hotel?"],
    "restaurant-pricerange":["What is the price range of the restaurant?"],
    "hotel-type": ["What type of hotel are you looking for?"],
    "attraction-type":["What type of attraction are you interested in?"],
    "hotel-book day":["On what day do you want to book the hotel?"],
    "restaurant-book day":["On what day do you want to book the restaurant?"],
    "hotel-book people": ["How many people are you booking the hotel for?"],
    "train-book people": ["How many people are you booking the train for?"],
    "restaurant-book people": ["How many people are you booking the restaurant for?"],
    "hotel-area":  ["What area is the hotel located in?"],
    "restaurant-area":  ["What area is the restaurant located in?"],
    "attraction-area":  ["What area is the attraction located in?"],
    "hotel-name":    ["What is the name of the hotel?"],
    "attraction-name":  ["What is the name of the attraction?"],
    "restaurant-name":  ["What is the name of the restaurant?"],
    "train-destination": ["What is the destination of the train?"],
    "taxi-destination":  ["What is the destination of the taxi?"],
    "taxi-departure":  ["What is the departure point of the taxi?"],
    "train-departure": ["What is the departure point of the train?"],
    "train-arriveby": ["What time does the train arrive by?"],
    "taxi-arriveby":  ["What time does the taxi arrive by?"],
    "train-leaveat":  ["What time does the taxi leave at?"],
    "taxi-leaveat": ["What time does the train leave at?"],
    "restaurant-food": ["What type of food does the restaurant serve?"],
    "restaurant-book time": ["What time do you want to book the restaurant for?"],
    "hotel-book stay": ["How long do you want to stay at the hotel?"],
    "hotel-parking": ["Does the hotel have parking?"],
    "hotel-stars": ["How many stars does the hotel have?"],
    "hotel-internet": ["Does the hotel have internet access?"],
    "train-day": ["On what day do you need to book a train?"],
}


mwoz_slots_to_qa_worst = {
    "hotel-pricerange": ["A?"],
    "restaurant-pricerange": ["B?"],
    "hotel-type": ["C?"],
    "attraction-type": ["D?"],
    "hotel-book day": ["E?"],
    "restaurant-book day": ["F?"],
    "hotel-book people": ["G?"],
    "train-book people": ["H?"],
    "restaurant-book people": ["I?"],
    "hotel-area": ["J?"],
    "restaurant-area": ["K?"],
    "attraction-area": ["L?"],
    "hotel-name": ["M?"],
    "attraction-name": ["N?"],
    "restaurant-name": ["O?"],
    "train-destination": ["P?"],
    "taxi-destination": ["Q?"],
    "taxi-departure": ["R?"],
    "train-departure": ["S?"],
    "train-arriveby": ["T?"],
    "taxi-arriveby": ["U?"],
    "train-leaveat": ["V?"],
    "taxi-leaveat": ["W?"],
    "restaurant-food": ["X?"],
    "restaurant-book time": ["Y?"],
    "hotel-book stay": ["Z?"],
    "hotel-parking": ["AA?"],
    "hotel-stars": ["AB?"],
    "hotel-internet": ["AC?"],
    "train-day": ["AD?"],
}


handmade_mwoz_intent_to_qa = {
    "find_hotel": ["is the intent to find a hotel?"],
    "book_hotel": ["is the intent to book a hotel?"],
    "find_train": ["is the intent to find a train?"],
    "book_train": ["is the intent to book a train?"],
    "find_attraction": ["is the intent to find an attraction?"],
    "find_restaurant": ["is the intent to find a restaurant?"],
    "book_restaurant": ["is the intent to book a restaurant?"],
    "find_hospital": ["is the intent to find a hospital?"],
    "book_taxi": ["is the intent to book a taxi?"],
    "find_taxi": ["is the intent to find a taxi?"],
    "find_bus": ["is the intent to search for a bus?"],
    "police": ["is the intent to search for a police station?"],
    "find_police": ["is the intent to search for a police station?"],
}

handmade_simm_slots_to_qa = {
    "num_tickets": ["how many tickets does the user want?"],
    "theatre_name": ["what is the chosen theater name?"],
    "date": ["what is the date?"],
    "movie": ["what is the movie?",
              "what movie does the user want to see?",
              "what movie did the user want to see?",
              "what movie was the user looking for?",
              "what was the name of the movie?",
              "what was the movie name?",
              "what was the movie the user was looking for?",
              "what was the movie the user wanted to see?",
              "what was the movie the user wanted?",
              "what title did the user want to see?",
              "what was the title of the movie?",
              "what was the title of the movie the user wanted to see?",
              "what was the title of the movie the user wanted?"],
    "time": ["what is the chosen time?",
             "what time did the user want to see the movie?",
             "what time did the user choose?",
             "what time did the user want to see the movie at?",
             "what is the user's chosen time?",
             "what is the time the user wanted to see the movie at?",
             ],
}

handmade_simm_intents_to_qa = {
    "BUY_MOVIE_TICKETS": ["is the intent for the user to buy movie tickets?"],
    "NONE": ["is the intent unknown?"],
}

handmade_simr_slots_to_qa = {
    "time": ["what is the user's chosen time?"],
    "rating": ["what is the user's chosen restaurant rating?"],
    "category": ["what is the preferred category?"],
    "location": ["what is the chosen location?"],
    "meal": ["what kind of meal?"],
    "price_range": ["what is the desired restaurant price range?"],
    "restaurant_name": ["what is the chosen restaurant name?"],
    "num_people": ["how many people will eat?"],
    "date": ["what is the user's desired date?"],
}

handmade_simr_intents_to_qa = {
    "FIND_RESTAURANT": ["is the intent to find a restaurant?"],
    "RESERVE_RESTAURANT": ["is the intent to reserve a restaurant?"],
    "NONE": ["is the intent unknown?"],
}

handmade_ff_boi_intents_to_qa = {
    "user_neutral_tell_joke": ["is the intent to ask the system to tell a joke?"],
    "user_inform_product_attribute": ["is the intent for the system to inform the user about a product attribute?"],
    "user_neutral_fun_fact": ["is the intent to ask for a fun fact?"],
    "user_neutral_who_do_you_work_for": ["is the intent to ask who the system works for?"],
    "user_qa_product_composition": ["is the intent to ask about the product's composition?"],
    "user_neutral_what_can_i_ask_you": ["is the intent to ask about what the system can do?"],
    "user_neutral_are_you_a_bot": ["is the intent to ask if the system is a bot?"],
    "user_neutral_who_made_you": ["is the intent to ask who made the system?"],
    "user_qa_product_measurement": ["is the intent to ask about the product's measurement?"],
    "user_neutral_how_old_are_you": ["is the intent to ask how old the system is?"],
    "user_neutral_greeting": ["is the intent to greet the system?"],
    "user_neutral_where_are_you_from": ["is the intent to ask where the system is from?"],
    "user_qa_product_description": ["is the intent to ask about the product's description?"],
    "user_request_get_products": ["is the intent to search for products?"],
    "user_qa_check_information": ["is the intent to ask about the product's information?"],
    "user_neutral_goodbye": ["is the intent to say goodbye to the system?"],
    "user_neutral_meaning_of_life": ["is the intent to ask about the meaning of life?"],
    "user_neutral_what_are_your_hobbies": ["is the intent to ask about the system's hobbies?"],
    "user_inform_product_id": ["is the intent to inform the system about a product id?"],
    "user_neutral_what_is_your_name": ["is the intent to ask the system's name?"],
    "user_qa_product_information": ["is the intent to ask about the product's information?"],
    "user_neutral_do_you_have_pets": ["is the intent to ask if the system has pets?"],
    "user_neutral_oos": ["is the intent out of scope?"],
    "select_article": ["is the intent to select an article?"],
    "ask_for_suggestions": ["is the intent to ask for suggestions?"],
    "add_to_cart": ["is the intent to add an item to the cart?"],
    "see_cart": ["is the intent to see the cart?"],
    "goes_well_with": ["is the intent to ask for items that go well with the selected item?"],
    "yes": ["is the intent to say yes?"],
    "no": ["is the intent to say no?"],
    "stop": ["is the intent to stop the interaction?"],
    "repeat": ["is the intent to ask the system to repeat the last utterance?"],
    "show_more": ["is the intent to ask the system to show more items?"],
    "help": ["is the intent to ask for help?"],
}


handmade_ff_boi_slots_to_qa = {
    'country_of_origin': ["what is the user's requested country of origin?"],
    'neckline': ["how should the neckline be?"],
    'short_description': ["what is the requested products's short description?"],
    'rise': ["what is the requested products's rise?"],
    'scent': ["what is the requested products's scent?"],
    'material_group': ["what is the group of the requested product's material?"],
    'size': ["what is the requested products's size?"],
    'bracelet\\wtype': ["what is the requested products's bracelet type?"],
    'movement': ["what is the requested products's movement?"],
    'face\\wshape': ["what is the user's face shape?"],
    'formulation': ["what is the requested products's formulation?"],
    'texture': ["what is the requested products's texture?"],
    'earring\\wtype': ["what is the requested product's earring type?"],
    'product_part': ["what is the requested product's part?"],
    'gender_name': ["what is the user's gender?"],
    'necklace\\wtype': ["what type should the necklace be?"],
    'number': ["what is the number?"],
    'product_measurement': ["what is the user's chosen product measurement?"],
    'is_animal': ["should the product be made of animals?"],
    'material_name': ["what should the material name be?"],
    'productid': ["what is the product id?"],
    'available_sizes': ["what are the available product sizes?"],
    'is_vintage': ["should the product be vintage?"],
    'colour': ["what is the requested product's colour?"],
    'length': ["what is the requested product's length?"],
    'product_attribute': ["what is the user's chosen product attribute?"],
    'volume': ["what is the requested product's volume?"],
    'season_name': ["what is the requested product's season?"],
    'shirt\\wstyle': ["what is the requested product's shirt style?"],
    'finish': ["what is the requested product's finish?"],
    'num': ["what is the number of the chosen product?"],
    'hat_style': ["what is the requested hat's style?"],
    'ring\\wtype': ["what is the requested ring type?"],
    'bracelet_type': ["what is the requested bracelet type?"],
    'coat\\wsilhouette': ["what is the coat's silhouette?"],
    'shoe\\wdetail': ["what is the shoe's detail?"],
    'heel_height': ["what should the heel height be?"],
    'shirt_style': ["what is the requested shirt's style?"],
    'sustainability\\wcertifications': ["what are the product's sustainability certifications?"],
    'category_gender_name': ["what is the chosen gender?"],
    'ring_type': ["what is the requested ring type?"],
    'category': ["what is the requested category?"],
    'dress_silhouette': ["what is the requested dress's silhouette?"],
    'hat\\wstyle': ["what is the requested hat's style?"],
    'sustainable\\wingredients': ["what are the product's sustainable ingredients?"],
    'face_shape': ["what is the user's face shape?"],
    'dress\\wsilhouette': ["what is the requested dress silhouette?"],
    'heel\\wheight': ["what is the requested heel height?"],
    'coat_silhouette': ["what is the requested coat silhouette?"],
    'lenses': ["what are the requested lenses?"],
    'min_base_price': ["what is the minimum base price?"],
    'occasion': ["what is the requested occasion?"],
    'necklace_type': ["what is the requested necklace type?"],
    'earring_type': ["what is the requested earring type?"],
    'brand_name': ["what is the requested brand?"],
    'sleeve\\wlength': ["what is the requested sleeve length?"],
    'fit': ["what is the requested fit?"],
    'shoe_detail': ["what is the requested shoe detail?"],
    'sleeve_length': ["what is the requested sleeve length?"],
    'frame': ["what is the requested frame?"],
    'condition': ["what is the requested condition?"],
    'is_multi_color': ["should the product be multi-coloured?"],
}


handmade_sgd_slots_to_qa = {
    'number_of_beds': ['how many beds should the room have?'],
    'number_of_tickets': ['how many tickets does the user want?'],
    'where_to': ['where does the user want to go?'],
    'rating': ['what is the rating?'],
    'from': ['where is the user coming from?'],
    'city': ['what is the desired city?'],
    'number_of_adults': ['how many adults should there be?'],
    'trip_protection': ['does the user want trip protection?'],
    'date': ['what is the requested date?'],
    'new_alarm_time': ['what is the new alarm time?'],
    'track': ['what is the requested track?'],
    'departure_time': ['what is the requested departure time?'],
    'to': ['where is the user going?'],
    'return_date': ['what is the requested return date?'],
    'is_unisex': ['is it unisex?'],
    'has_seating_outdoors': ['should it have outdoor seating?'],
    'place_name': ['what is the requested place name?'],
    'check_in_date': ['what is the check in date?'],
    'number_of_rooms': ['how many rooms should there be?'],
    'end_date': ['what is the end date?'],
    'album': ['what is the requested album?'],
    'show_time': ['what is the time of the show?'],
    'destination_airport': ['what is the destination airport?'],
    'property_name': ['what is the requested property name?'],
    'stay_length': ['what is the length of the stay?'],
    'date_of_journey': ['what should the date of the journey be?'],
    'device': ['what is the requested device?'],
    'stylist_name': ['what is the name of the stylist?'],
    'category': ['what is the requested category?'],
    'show_type': ['what is the type of the show?'],
    'start_date': ['what should the start date be?'],
    'star_rating': ['what is the rating in stars?'],
    'smoking_allowed': ['is smoking allowed?'],
    'appointment_time': ['what is the time of the appointment?'],
    'departure_date': ['what is the date of the departure?'],
    'receiver': ['who is the receiver?'],
    'year': ['what is the requested year?'],
    'location': ['where will it be located?'],
    'pickup_time': ['what is the pickup time?'],
    'restaurant_name': ['what is the chosen restaurant name?'],
    'event_type': ['what is the type of the event?'],
    'therapist_name': ['what is the name of the therapist?'],
    'genre': ['what is the requested genre?'],
    'to_city': ['what is the destination city?'],
    'num_passengers': ['how many passengers should there be?'],
    'price_range': ['what is the requested price range?'],
    'has_laundry_service': ['should it have laundry service?'],
    'theater_name': ['what is the name of the theater?'],
    'has_garage': ['should it have garage?'],
    'number_of_seats': ['how many seats should there be?'],
    'free_entry': ['should it have free entry?'],
    'amount': ['what is the requested amount?'],
    'intent': ['what is the intent?'],
    'appointment_date': ['what should the appointment date be?'],
    'pickup_location': ['what is the desired pickup location?'],
    'number_of_baths': ['how many baths should there be?'],
    'visit_date': ['what is the date of visit?'],
    'car_type': ['what type of car does the user want?'],
    'contact_name': ['what is the contact name?'],
    'starring': ['who should star in it?'],
    'has_vegetarian_options': ['should it have vegetarian options?'],
    'time': ['what is the requested time?'],
    'airlines': ['what are the airlines?'],
    'class': ['what is the requested class?'],
    'area': ['what is the area?'],
    'ride_type': ['what is the type of ride?'],
    'good_for_kids': ['is it good for kids?'],
    'from_city': ['what is the origin city?'],
    'private_visibility': ['should the visibility be private?'],
    'destination': ['what is the destination?'],
    'in_unit_laundry': ['what is the laundry unit?'],
    'title': ['what is the requested title?'],
    'seating_class': ['what is the class of the seating?'],
    'check_out_date': ['what is the date of checkout?'],
    'origin_airport': ['what is the origin airport?'],
    'directed_by': ['who is the director?'],
    'additional_luggage': ['should there be additional luggage?'],
    'subtitle_language': ['what is the requested subtitle language?'],
    'add_insurance': ['should it add insurance?'],
    'artist': ['what is the requested artist?'],
    'type': ['what is the type?'],
    'show_date': ['what is the show date?'],
    'payment_method': ['what is the user\'s preferred payment method?'],
    'event_name': ['what is the name of the event?'],
    'journey_start_time': ['what is the start time?'],
    'cast': ['what is the cast?'],
    'new_alarm_name': ['what is the name of the new alarm?'],
    'movie_name': ['what is the name of the movie?'],
}

handmade_sgd_intents_to_qa = {
    'PlaySong': ['is the intent for the system to play a song?'],
    'ReserveRestaurant': ['is the intent for the system to reserve a restaurant?'],
    'FindAttractions': ['is the intent to find attractions?'],
    'GetEvents': ['is the intent to get events?'],
    'CheckBalance': ['is the intent to check the balance?'],
    'FindProvider': ['is the intent to find a provider?'],
    'FindMovies': ['is the intent to find movies?'],
    'GetRide': ['is the intent to get a ride?'],
    'SearchHouse': ['is the intent to search for a house?'],
    'ReserveRoundtripFlights': ['is the intent to reserve a roundtrip flight?'],
    'GetTimesForMovie': ['is the intent to get the movie times?'],
    'PlayMedia': ['is the intent to play media?'],
    'SearchRoundtripFlights': ['is the intent to search for roundtrip flights?'],
    'ScheduleVisit': ['is the intent to schedule a visit?'],
    'PlayMovie': ['is the intent to play a movie?'],
    'BookAppointment': ['is the intent to book an appointment?'],
    'BuyBusTicket': ['is the intent to buy a bus ticket?'],
    'SearchOnewayFlight': ['is the intent to search for a one way flight?'],
    'FindApartment': ['is the intent to find an apartment?'],
    'FindRestaurants': ['is the intent to find a restaurant?'],
    'FindBus': ['is the intent to find a bus?'],
    'ReserveHotel': ['is the intent to reserve a hotel?'],
    'ReserveCar': ['is the intent to reserve a car?'],
    'GetAvailableTime': ['is the intent to get the available time?'],
    'GetWeather': ['is the intent to get the weather?'],
    'BookHouse': ['is the intent to book a house?'],
    'GetCarsAvailable': ['is the intent to get the cars available?'],
    'AddEvent': ['is the intent to add an event?'],
    'FindEvents': ['is the intent to find events?'],
    'TransferMoney': ['is the intent to transfer money?'],
    'BuyEventTickets': ['is the intent to buy event tickets?'],
    'ReserveOnewayFlight': ['is the intent to reserve a one way flight?'],
    'NONE': ['is the intent unknown?'],
    'LookupMusic': ['is the intent to look up music?'],
    'LookupSong': ['is the intent to look up a song?'],
    'GetEventDates': ['is the intent to get the event dates?'],
    'SearchHotel': ['is the intent to search for a hotel?']
}
